services:
  - type: web
    name: medicine-finder
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: USE_S3_STORAGE
        value: "0"
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_S3_ENDPOINT_URL
        sync: false
      - key: AWS_S3_REGION_NAME
        sync: false
      - key: AWS_S3_ACCESS_KEY_ID
        sync: false
      - key: AWS_S3_SECRET_ACCESS_KEY
        sync: false
